Add CI/CD for Docker build and Sonar
usdot-jpo-ode/jpo-ode pull request #498
Opened 2023-03-23 13:07 UTC by SaikrishnaBairamoni

# PR Details
This PR is to add the GitHub actions workflows for both docker hub build and to run sonar scan analysis for  publishing  static reports on sonar cloud dashboard.
## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[ODE Contributing Guide](https://github.com/usdot-jpo-ode/jpo-ode/blob/bugfix/Pull_request_template/docs/contributing_guide.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-03-24 13:41 UTC, codygarver requested changes

2023-03-24 13:41 UTC, codygarver commented on .github/workflows/dockerhub.yml
> +      - "dev"
@SaikrishnaBairamoni change to `develop`

2023-03-24 13:41 UTC, codygarver requested changes

2023-03-24 14:43 UTC, SaikrishnaBairamoni commented on .github/workflows/ci.yml
> +          mvn install -DskipTests
Removed

2023-03-24 14:44 UTC, SaikrishnaBairamoni commented on .github/workflows/dockerhub.yml
> +          tags: usdotjpoode/jpo-ode:${{ github.ref_name }}
updated branch name to develop

2023-03-24 15:35 UTC, codygarver commented on .github/workflows/dockerhub.yml
> +          file: ./Dockerfile
@SaikrishnaBairamoni  I don't think you need it because the defaults are the same values you have set here. Can you try it without it?

2023-03-24 15:37 UTC, codygarver requested changes

2023-03-28 19:05 UTC, SaikrishnaBairamoni commented on .github/workflows/dockerhub.yml
> +          file: ./Dockerfile
@codygarver it worked without this parameters. build was not broken

2023-03-28 19:31 UTC, codygarver requested changes

2023-03-28 19:31 UTC, codygarver commented on .github/workflows/dockerhub.yml
> +      - "dev"
@SaikrishnaBairamoni this should be `develop`

2023-03-28 19:47 UTC, merged